apiVersion: v1
kind: Service
metadata:
  name: skcafeapp
  labels:
    app: cafe-app
spec:
  selector:
    app: cafe-app 

  ports:
    - port: 80
      targetPort: 80

  type: LoadBalancer